language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t benbh1270/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true benbh1270/docker-react npm run test